replicaCount: 1

image:
  repository: directus/directus
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

base:
  publicHost: ""
  # fatal, error, warn, info, debug, trace, silent
  logLevel: "debug"
  MAX_RELATIONAL_DEPTH: ""
  maxRelationalDepth: 10

storage:
  # local, s3
  locations: {}
  local:
    root: ""
  s3:
    accessKey: ""
    accessKeySecret: ""
    bucket: ""
    region: ""
    endpoint: ""
    forcePathStyle: false

cache:
  # memory, redis
  type: "memory"
  redis:
    url: ""
    host: ""
    port: ""
    password: ""

auth:
  # github, ldap
  providers: {}
  github:
    clientId: ""
    clientSecret: ""
  ldap:
    url: ""
    bindDN: ""
    bindPassword: ""
    userDN: ""
    userAttribute: ""
    mailAttribute: ""
    firstAttribute: ""
    lastAttribute: ""
    defaultRoleID: ""

database:
  # mysql
  type: "mysql"
  mysql:
    host: ""
    port: ""
    database: ""
    user: ""
    password: ""

mail:
  enable: false
  verifySetup: true
  from: ""
  smtp:
    host: ""
    port: ""
    user: ""
    password: ""
    secure: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  #  hosts:
  #    - host: example.com
  #      paths:
  #        - path: /
  #          pathType: ImplementationSpecific

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
