---
{{ if not .Values.server.volume.config.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aria2-pro.server.volume.config.name" . }}
  labels:
    {{- include "aria2-pro.server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.volume.config.storage }}
  storageClassName: {{ .Values.server.volume.config.storageClassName }}
{{ end }}

---
{{ if not .Values.server.volume.downloads.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aria2-pro.server.volume.downloads.name" . }}
  labels:
    {{- include "aria2-pro.server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.volume.downloads.storage }}
  storageClassName: {{ .Values.server.volume.downloads.storageClassName }}
{{ end }}
