apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aria2-pro.server.fullname" . }}
  labels:
    {{- include "aria2-pro.server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "aria2-pro.server.fullname" . }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      {{- include "aria2-pro.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aria2-pro.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "p3terx/aria2-pro:latest"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port.rpc }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: RPC_SECRET
              value: {{ .Values.common.secret | quote }}
            - name: RPC_PORT
              value: {{ .Values.server.port.rpc | quote }}
            - name: LISTEN_PORT
              value: {{ .Values.common.listenPort | quote }}
            - name: DISK_CACHE
              value: {{ .Values.common.diskCache | quote }}
            - name: IPV6_MODE
              value: {{ .Values.common.ipv6 | quote }}
            - name: CUSTOM_TRACKER_URL
              value: {{ .Values.common.trackerUrl | quote }}
            - name: TZ
              value: {{ .Values.common.tz | quote }}
            - name: UPDATE_TRACKERS
              value: {{ .Values.common.updateTrackers | quote }}
      volumes: {}
        {{- if .Values.server.volume.config.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.server.volume.config.existingClaim }}
        {{- end }}
        {{- if .Values.server.volume.downloads.existingClaim }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Values.server.volume.downloads.existingClaim }}
        {{- end }}
  volumeClaimTemplates:
    {{- if not .Values.server.volume.downloads.existingClaim }}
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.server.volume.config.storage }}
        storageClassName: {{ .Values.server.volume.config.storageClassName }}
    {{- end }}
    {{- if not .Values.server.volume.downloads.existingClaim }}
    - metadata:
        name: downloads
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.server.volume.downloads.storage }}
        storageClassName: {{ .Values.server.volume.downloads.storageClassName }}
    {{- end }}
