apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aria2-pro.web.fullname" . }}
  labels:
    {{- include "aria2-pro.web.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aria2-pro.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aria2-pro.web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}-web
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "p3terx/ariang:latest"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 6880
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
