apiVersion: v1
kind: Service
metadata:
  name: {{ include "aria2-pro.web.fullname" . }}
  labels:
    {{- include "aria2-pro.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aria2-pro.web.selectorLabels" . | nindent 4 }}
