imagePullSecrets: []
imagePullPolicy: IfNotPresent

common:
  secret: ""
  listenPort: "6888"
  diskCache: "64M"
  ipv6: "false"
  UPDATE_TRACKERS: "false"
  trackerUrl: "https://trackerslist.com/all_aria2.txt"
  autoUpdateTracker: "true"
  tz: "Asia/Shanghai"

server:
  port:
    rpc: 6800

  podAnnotations: { }
  podSecurityContext: { }
  # fsGroup: 2000

  volume:
    config:
      storage: 100Mi
      storageClassName: ""
      existingClaim: ""
    downloads:
      storage: 10Gi
      storageClassName: ""
      existingClaim: ""

  securityContext: { }
    # capabilities:
    #   drop:
    #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  service:
    type: ClusterIP

  ingress:
    enabled: false
    className: ""
    annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
    tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local


web:
  service:
    type: ClusterIP

  ingress:
    enabled: false
    className: ""
    annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
    tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
